### ISSUE TITLE
Make it possible to output scss entirely as mixins instead of classes

### ISSUE THREAD

**Issue by luksak** [jkphl/svg-sprite#103] opened 2015-08-18 10:11 UTC
Because [this issue] (https://github.com/sass/sass/issues/1050) is no resolved yet, I am unable to use the generated scss using @extend inside media queries. Could we add a possibility to output the scss file entirely as mixins?

**Comment by jkphl** [comment] 2015-08-18 12:42
@luksak Have you [already checked](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#specific-mode-properties) the `mode.<mode>.mixin` option of «css» / «view» sprites? This is exactly what it is meant for. In fact there should be only very few situations where a CSS property is
* not constant for all breakpoints (like `background-image` or `background-repeat`) and
* not individual for each breakpoint anyway (potentially `background-size`) so a mixin wouldn't help either.

Currently, a dataUri based background image and the constant `no-repeat` are the only properties I can think of that would make sense in a mixin. And this is exactly what [the default template is catering for](https://github.com/jkphl/svg-sprite/blob/master/tmpl/css/sprite.scss#L2). Please let me know if you've got any more particular suggestions.

Cheers, Joschi

**Comment by luksak** [comment] 2015-08-18 16:37
Well, this outputs the common properties into a mixin. Not the single images. Let's say I have an element I want to add an icon to like this:

```
.close {
  @extend .svg-images--close-s;
  @extend .svg-images--close-s-dims;
}
```
Works perfectly. But If I want to use different icons for another breaktpoint this doesn't work:

```
.close {
  @extend .svg-images--close-s;
  @extend .svg-images--close-s-dims;

  @media (min-width: 960px) {

    @extend .svg-images--close-l;
    @extend .svg-images--close-l-dims;
  }
}
```
It throws this error: 
```
You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
```

However this would work perfectly:

```
.close {
  @include svg-images--close-s;
  @include svg-images--close-s-dims;

  @media (min-width: 960px) {

    @include svg-images--close-l;
    @include svg-images--close-l-dims;
  }
}
```

So outputting all SCSS code as mixins instead of classes would solve this. How can I achieve this?

**Comment by jkphl** [comment] 2015-08-27 16:22
@luksak Well, first of all sorry for not being more responsive. The whole office was off grid for 2 days due to a hardware failure ...

You could surely achieve what you want, but you'd have to deep-dive into the [scss Mustache template](https://github.com/jkphl/svg-sprite/blob/master/tmpl/css/sprite.scss) and write your own version of it. I'm sorry but I'm currently not able to help you with this — wrapping your head around that templating thing is not exactly what I'd call trivial. You will want to have a look into the [templating hints](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) before.

I'd be interested in your solution, so please let me know if you succeed. I'll close this issue for now, but please feel free to re-open it if you run into troubles.

Cheers, Joschi

**Comment by luksak** [comment] 2015-08-28 08:46
I would totally try to do this. But there is an issue with the variables passed to the template. I am only getting the selectors with the dot:

```
{{/hasMixin}}{{#shapes}}{{#selector.shape}}{{expression}}{{^last}},
{{/last}}{{/selector.shape}} {
	{{^hasCommon}}{{#hasMixin}}@include {{mixinName}};{{/hasMixin}}{{^hasMixin}}@extend %{{commonName}};{{/hasMixin}}
	{{/hasCommon}}background-position: {{position.relative.xy}};{{#dimensions.inline}}
	width: {{width.outer}}px;
	height: {{height.outer}}px;{{/dimensions.inline}}
}{{#dimensions.extra}}
```

{{expression}} seems to contain the selector. How can I replace a string here? This way I could replace "." with "@mixin " and the issue was solved for now.

Please reopen the issue since this is not fixed.

**Comment by jkphl** [comment] 2015-08-28 10:44
hi @luksak,

as far as I understand you'd probably need to write and pass in a custom function [like e.g. the builtin `classname` function](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md#classname) which takes the selector and replaces the dot as you said. Please see the [section about custom templating variables](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#custom-templating-variables) in the docs to get an idea of how this might look (the example shows a function that replaces the `.svg` extension against `.png`).

As this is neither a bug nor an enhancement but rather an individual templating solution for your particular situation I prefer to not see this as an issue of public interest that should be regarded unresolved. I hope for you understanding. As soon as you encounter any problems that relate to true bugs in *svg-sprite* I'll happily reopen this issue.

Cheers, Joschi

**Comment by mlarcher** [comment] 2015-12-03 09:16
I am facing the same issue and I believe the behaviour described by @luksak would be a neat enhancement, if not a required feature. It would solve the limitations of @extend while keeping the styling on the css side of things instead of resorting to adding style only related classes in the markup.

Any chance you reconsider your position on the matter ?

**Comment by jkphl** [comment] 2015-12-03 09:28
@mlarcher As I detailed before, your goal could most likely be achieved out of the box with a combination of a custom template and an additional auxiliary function. It's definitely not a requirement for the core (although one could of course always add even more config options and switches ...).

I'm currently planning a major rewrite of *svg-sprite* and I may consider such an extension then (I'll thus re-open this issue as a reminder), but I won't work on it on the short run, sorry. In case you're going to develop a working template / function example, I'd be happy if you shared it with others!

Thanks for your patience! :)

**Comment by mlarcher** [comment] 2015-12-03 21:25
Thank you for reopening. It may be best to wait fr the rewrite before proceeding with this feature, but it's nice to know the issue is open and won't be forgotten.
Cheers!

**Comment by starksider** [comment] 2015-12-22 18:03
Hi, everyone! @luksak you can achive this
```
 .close {
  @include svg-images--close-s;
  @include svg-images--close-s-dims;

  @media (min-width: 960px) {

    @include svg-images--close-l;
    @include svg-images--close-l-dims;
  }
}
```
by adding **prefix: '@mixin svg-%s'** property of config object:
```
var config                  = {
    mode                    : {
        <mode>              : {
            ...
            prefix          : "@mixin svg-%s",                     // Prefix for CSS selectors
            ...
        }
    }
}
```
It works great for me

**Comment by jkphl** [comment] 2015-12-22 18:20
Awesome solution, @starksider. Thanks for sharing!

**Comment by jkphl** [comment] 2016-05-14 15:33
After reading through this issue again, it seems to me that @starksider's solution is far more efficient than any core extension would ever be. I strongly recommend following his suggestion (and will therefore close this issue again).

**Closed by jkphl** 2016-05-14 15:33 UTC
Labels: enhancement, question
