### ISSUE TITLE
Substitution strings in log not replaced correctly when using the command line version

### ISSUE THREAD

**Issue by dweidner** [jkphl/svg-sprite#279] opened 2018-10-25 12:15 UTC
I get the following output if I run the latest command line version of svg-sprite with debug flag set:

```sh
{"message":"Started logging","level":"debug"}
{"message":"Prepared general options","level":"debug"}
{"message":"Prepared `shape` options","level":"debug"}
{"message":"Prepared `svg` options","level":"debug"}
{"message":"Prepared `mode` options","level":"debug"}
{"message":"Prepared `variables` options","level":"debug"}
{"message":"Initialized spriter configuration","level":"verbose"}
{"message":"Created processing queue instance","level":"debug"}
{"message":"Created spriter instance","level":"info"}
{"level":"info","message":"Compiling %d shapes ..."}
{"message":"Created layouter instance","level":"debug"}
{"level":"info","message":"Laying out «%s» sprite («%s» mode)"}
{"level":"debug","message":"Created «%s» sprite instance («%s» mode)"}
{"level":"verbose","message":"Created «%s» SVG sprite file («%s» mode)"}
{"level":"info","message":"Finished %s sprite compilation"}
{"message":"Created 1 x SVG","level":"info"}
{"level":"verbose","message":"Created %s: %s"}
```

I am currently using node in version 8.12.0, npm 6.4.1 on macOS Mojave. I was able to reproduce the issue in a simple test project:

```sh
$ npm init -y
$ npm install -D svg-sprite
```

```json
{
  "name": "svg-sprite-test",
  "version": "0.0.1",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "sprite": "svg-sprite --log debug --symbol --symbol-dest assets src/icons/*.svg"
  },
  "author": "",
  "license": "MIT",
  "keywords": [],
  "description": "",
  "devDependencies": {
    "svg-sprite": "^1.5.0"
  }
}
```

```sh
$ npm -s run sprite
$ npx svg-sprite --log debug --symbol --symbol-dest assets src/icons/*.svg
```

Both produce the same output. Is it just me? Wanted to see the amount of saved bytes while playing with some of the svgo settings in my actual project.

**Comment by louh** [comment] 2019-08-08 17:46
This is happening for me too (and even though I thumb's-upped this a while back, I was hoping to come back and see if any progress has been made on this).

I've looked into this a little bit, and it seems the issue is that the [`winston`](https://www.npmjs.com/package/winston) logging library was upgraded to version 3.x which [introduced a lot of breaking changes](https://github.com/winstonjs/winston/blob/HEAD/UPGRADE-3.0.md) that were not [addressed in `svg-sprite`](https://github.com/jkphl/svg-sprite/blob/6966592489dfcf2cd9ed2bba500cb8ee31c00b9c/lib/svg-sprite/config.js#L99-L110).

As I have [some experience with `winston`](https://github.com/streetmix/streetmix/blob/443488beeeaf00196deb57cca34567e487de9f83/lib/logger.js) I can offer to create a pull request to solve this issue if @jkphl is open to this. We use `svg-sprite` frequently to "compile" SVG sprites (https://github.com/streetmix/illustrations) and the lack of good log output is really unfortunate.

Let me know if I can help!

**Comment by jkphl** [comment] 2019-08-08 17:49
@louh Your help would be highly appreciated as I currently don't have any capacity to work on my OS projects, unfortunately. Thanks a lot! 🙏

**Closed** 2020-01-18 16:19 UTC
