### ISSUE TITLE
Move phantomJs to devdependencies

### ISSUE THREAD

**Issue by pierre-hilt** [jkphl/svg-sprite#299] opened 2019-11-12 11:02 UTC
Hello,

for now phantomJs is set as a depdency. So that when we install svg-sprite it will download PhantomJS binary (and we dont need it).

I would like to propose to move to devDependency.

Best regards,

Pierre

**Comment by jkphl** [comment] 2019-11-18 14:41
Duplicate of #254

**Closed by jkphl** 2019-11-18 14:41 UTC
Labels: duplicate
