### ISSUE TITLE
Malformed inline SVG <symbol> sprite

### ISSUE THREAD

**Issue by kinday** [jkphl/svg-sprite#61] opened 2015-03-02 20:44 UTC
Hi!

I’m trying to generate an inline `<symbol>` sprite and can’t get valid SVG markup.

For some reason `svg-sprite` returns markup where all elements inside a `<symbol>` are nested one into another.

```svg
<!-- source -->
<svg>
  <symbol>
    <g>
      <path></path>
      <path></path>
    </g>
  </symbol>
</svg>

<!-- svg-sprite output -->
<svg>
  <symbol>
    <g>
      <path>
        <path></path>
      </path>
    </g>
  </symbol>
</svg>
```

I get this result on `node v0.12.0` on either `OS X 10.10` or `Ubuntu 14.04`.

I’ll share any details you might need to reproduce and solve the issue.

__UPD:__ If I pass the same files to `gulp-svg-sprite` the problem goes away. `<path>` tags are self-closed and DOM tree is ok.

**Comment by jkphl** [comment] 2015-03-02 21:08
Hey @kinday,

thanks for reporting this. I'm happy to help you solve your problem. However, I will be totally overloaded until Friday so I can't do anything before the weekend. Thanks for your patience!

Cheers,
Joschi

**Comment by jkphl** [comment] 2015-03-08 10:05
> UPD: If I pass the same files to gulp-svg-sprite the problem goes away. <path> tags are self-closed and DOM tree is ok.

Interesting — especially because *gulp-svg-sprite* does nothing else but employ *svg-sprite* internally. Could you please send me your source file SVGs and you svs-sprite configuration to joschi [at] kuphal [dot] net. I'll try to reproduce the problem.

**Comment by jkphl** [comment] 2015-04-09 23:00
@kinday Is this still of any relevance for you?

**Comment by jkphl** [comment] 2015-04-18 22:41
@kinday I'll close this for now. Please feel free to reopen the issue in case you still got problems.

**Closed by jkphl** 2015-04-18 22:41 UTC
Labels: question
