### ISSUE TITLE
Why is `phantomjs-prebuilt` a direct dependency and not a devDependency?

### ISSUE THREAD

**Issue by mlunoe** [jkphl/svg-sprite#222] opened 2017-02-28 18:42 UTC
I don't see any reason why this should be part of the direct dependencies.
Could we move this to devDependencies?

**Comment by jkphl** [comment] 2017-02-28 18:44
@mlunoe Duplicate of https://github.com/jkphl/svg-sprite/issues/100, please see there for details.

**Closed by jkphl** 2017-02-28 18:44 UTC
Labels: question
