### ISSUE TITLE
How do I configure svgo settings from CLI

### ISSUE THREAD

**Issue by Pittan** [jkphl/svg-sprite#218] opened 2017-02-09 07:26 UTC
I want to configure svgo because I have to disable `convertTransform` option.
But it seems convertTransform option is not disabled.  
I generated JSON configuration file in http://jkphl.github.io/svg-sprite/ .

```
{
  "transform": [
    {
      "svgo": {
        "plugins": [
          {
            "removeViewBox": true
          },
          {
            "convertTransform": false
          },
          {
            "moveGroupAttrsToElems": true
          },
          {
            "removeRasterImages": true
          }
        ]
      }
    }
  ],
  "mode": {
    "symbol": {
      "dest": ".",
      "sprite": "src/viewer/image/spritesheet.svg",
      "inline": true,
      "example": {
        "dest": "src/viewer/svg-sprite.html"
      }
    }
  }
}
```

**Comment by jkphl** [comment] 2017-02-09 08:07
@Pittan This might be a duplicate of https://github.com/jkphl/svg-sprite/issues/199. I'm on holidays right now, will try to look at it as soon as possible.

**Comment by Pittan** [comment] 2017-02-09 10:11
Oh... sorry 😢 
Have a nice holiday 🍹

**Comment by jkphl** [comment] 2017-02-09 16:02
@Pittan だいじょうぶ ☺ありがとう

**Comment by Pittan** [comment] 2017-04-07 21:29
Any update for this?😢

**Comment by jkphl** [comment] 2017-04-08 07:01
@Pittan I'm sorry but I'm still stuck in a very workload heavy project and the organisation of several events. I'd love to find some time for my OSS projects but right now I don't see a chance, I'm sorry. Please bear with me.

**Comment by mstoltenburg** [comment] 2017-04-13 11:16
@Pittan I had the same Problem. The solution for me was to put the config for SVGO in a separate file and use `svg-sprite --config svg-sprite.json --shape-transform-svgo svgo.json`

**svg-sprite.json**
```
{
  "mode": {
    "symbol": {
      "dest": ".",
      "sprite": "src/viewer/image/spritesheet.svg",
      "inline": true,
      "example": {
        "dest": "src/viewer/svg-sprite.html"
      }
    }
  }
}
```

**svgo.json**
```
{
  "plugins": [
    {"removeViewBox": true},
    {"convertTransform": false},
    {"moveGroupAttrsToElems": true},
    {"removeRasterImages": true}
  ]
}
```

**Comment by Pittan** [comment] 2017-04-14 04:09
@mstoltenburg This solution works perfectly!! Thank you 🎉 🌮 🍙 🏯

**Comment by jkphl** [comment] 2017-05-30 21:03
@Pittan @mstoltenburg As you guys seem to have found a working solution (thanks for sharing, Moritz!) I will close this issue for now. I plan to start a complete rewrite shortly and probably go for an all external, JSON style configuration for the CLI then, so no reason to spend too much effort into this anymore. Thanks for your support!

**Closed by jkphl** 2017-05-30 21:03 UTC
Labels: enhancement
