### ISSUE TITLE
would you move the phantomjs dependency to devDependencies? 

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#239] opened 2017-07-25 23:48 UTC
would you move the [phantomjs][0] dependency to devDependencies? 

[0]: https://github.com/jkphl/svg-sprite/blob/master/package.json#L49

**Comment by jkphl** [comment] 2017-07-26 05:25
@iambumblehead Duplicate of #100, pls see there for details.

**Closed by jkphl** 2017-07-26 05:25 UTC
Labels: duplicate

**Comment by iambumblehead** [comment] 2017-07-26 18:56
@jkphl thanks for the response --understood :)
