### ISSUE TITLE
PhantomJS should be registered as devDependency

### ISSUE THREAD

**Issue by nicolas-goudry** [jkphl/svg-sprite#211] opened 2016-12-27 11:59 UTC
Hi,

I’m using `svg-sprite` through `gulp-svg-sprite` and everything works well, except that PhantomJS is always downloaded on our CI because it is registered as dependency.

I didn’t check the whole code, but I think you’re only using it for your tests, so it shouldn’t be a dependency but a devDependency.

What do you think?

**Comment by jkphl** [comment] 2016-12-27 12:02
@nicolas-goudry Duplicate of #100, pls see there for details. On another note, I'll *probably* start a rewrite of *svg-sprite* this week and try to split out PhantomJS.

**Closed by jkphl** 2016-12-27 12:02 UTC

**Comment by nicolas-goudry** [comment] 2016-12-29 17:58
Thanks for your answer! Will see that later then, it’s not a huge matter 😃
