### ISSUE TITLE
Malforded IDs generated

### ISSUE THREAD

**Issue by mintuz** [jkphl/svg-sprite#101] opened 2015-07-31 09:59 UTC
Using the following config, chunk filenames are passed in within the generator callback.

## Config

```
var config = {
      "shape": {
        "id": {
          "generator": function(beep) {
            console.log(beep);
            return "beep";
          }
        }
      },
      "mode": {
        "symbol": {
          "dest": destSvgDir,
          "prefix": ".test-%s",
          "sprite" : folder + '.svg',
          "inline": true,
          "example": true
        }
      }
    };

    return gulp.src(srcSvgDir, {base: srcSvgDir})
      .pipe(svgSprite(config))
      .pipe(gulp.dest(destSvgDir));
```

## Chunk File Names

```
tops-play.svg
ag.svg
svg
s.svg
svg
.svg
g
league.svg
n.svg
union.svg
ut.svg
g.svg
ng.svg
-medal.svg
g
r.svg
-data.svg
-personality.svg
.svg
ngs-tables.svg
ng.svg
tennis.svg
ndo.svg
.svg
down.svg
ers.svg
lon.svg
g
-review.svg
ball.svg
lifting.svg
.svg
-sports.svg
record.svg
ing.svg
-flag.svg
```

**Comment by jkphl** [comment] 2015-08-11 21:59
Hi @mintuz,

I'm sorry, but I'm not able to reproduce this. Using your example config I just get the sprite that I would expect to get (although there's of course no sense in naming all the shapes the same, i.e. "beep"). Could you please provide more details? Which platform / versions are you working on? Obviously you're using the Gulp wrapper (the issue should've rather gone [here](https://github.com/jkphl/gulp-svg-sprite/issues) then btw.).

Cheers, Joschi

**Comment by jkphl** [comment] 2015-09-18 19:25
@mintuz Any news on this one?

**Comment by mintuz** [comment] 2015-09-19 08:56
Hey, yes I got it working in the end, it was to do with using svgmin first.

**Comment by jkphl** [comment] 2015-09-19 09:01
Ah, great, thanks for letting me know. Will close this one then ...

**Closed by jkphl** 2015-09-19 09:01 UTC
Labels: bug
