### ISSUE TITLE
SVG Stack link is a 404

### ISSUE THREAD

**Issue by NKjoep** [jkphl/svg-sprite#157] opened 2016-05-12 07:30 UTC
SVG Stack link in the readme points to this

[http://simurai.com/blog/2012/04/02/svg-stacks/](http://simurai.com/blog/2012/04/02/svg-stacks/) 

and it is a 404.

**Comment by jkphl** [comment] 2016-05-12 07:34
Thanks for reporting @NKjoep. However, this is a duplicate of #69 and has already been fixed in the master branch. I'll hopefully be able to push out a new release soon.

**Closed by jkphl** 2016-05-12 07:34 UTC
Labels: duplicate

**Comment by NKjoep** [comment] 2016-05-12 07:46
oh cool! :) I tried to use the search but I couldn't find it! 👍

**Comment by jkphl** [comment] 2016-05-12 07:48
Yeah, it's a little hard to find as it was reported in another repo (the Grunt wrapper). But fortunately my memories jumped in. ;)
