### ISSUE TITLE
linear gradient in symbol (FF)

### ISSUE THREAD

**Issue by Muskos** [jkphl/svg-sprite#197] opened 2016-10-17 09:33 UTC
Did you see this bug on FF?
http://stackoverflow.com/questions/24806913/how-can-i-refer-to-an-internal-gradient-definition-inside-an-svg-sprite-symbol
Have you some options or issue for this?

**Comment by jkphl** [comment] 2016-10-20 10:53
@Muskos There have been sum bug reports on gradients with `<symbol>` sprites in the past, yes, but I didn't take any notice of this solution, so thanks for the heads-up!

Other than that, I don't really understand your question?! What do you expect me to do or answer? Obviously it is possible to use `<symbol>` sprites with gradients, but the solution is more of a CSS one (applied from outside the sprite) rather than something *svg-sprite* would have to commence. Please correct me if I'm wrong though ...?

**Comment by Muskos** [comment] 2016-10-21 07:41
I've faced a problem when built my application. I've got this code http://codepen.io/Muskos/pen/dpjvvj 
After that, I need to change this code manually to get this http://codepen.io/Muskos/pen/WGaGmN
And i think you can improve this, can't you? Maybe some option should be added in your plugin to move gradient from `<symbol>`. Chrome, Edge, Mozilla sees this construction well. I don't know about ie :)

**Comment by jkphl** [comment] 2016-10-21 14:57
@Muskos Thanks for clarifying. So basically what you request is a duplicate of #74, correct? I'm aware of the fact that this would probably be useful for some folks — but well, I didn't find the time to work on it yet (and probably won't in the near future due to massive overload). Please feel free to send a PR — otherwise I have to ask for your patience. Closing this one in favour of #74 ... Thanks for reporting (again).

**Closed by jkphl** 2016-10-21 14:57 UTC
Labels: question
